# Generated by Django 4.0.3 on 2022-03-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_makepostcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='big_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
